/// Flutter icons JobTimerIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  JobTimerIcons
///      fonts:
///       - asset: fonts/JobTimerIcons.ttf
///
///
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class JobTimerIcons {
  JobTimerIcons._();

  static const _kFontFam = 'JobTimerIcons';
  static const String? _kFontPkg = null;

  static const IconData okCircled = IconData(
    0xe800,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );

  static const IconData angleDoubleRight = IconData(
    0xf101,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
}
