name: job_timer
description: Job Timer.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  asuka: ^2.0.0+1
  bloc: ^8.0.3
  cupertino_icons: ^1.0.5
  equatable: ^2.0.3
  firebase_auth: ^3.3.19
  firebase_core: ^1.17.1
  fl_chart: ^0.51.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_modular: ^5.0.2
  google_sign_in: ^5.3.2
  isar: ^2.5.0
  isar_flutter_libs: ^2.5.0
  modular_bloc_bind: ^1.0.1
  path_provider: ^2.0.10
  validatorless: ^1.2.1

dev_dependencies:
  build_runner: ^2.1.11
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  isar_generator: ^2.5.0

flutter:
  uses-material-design: true
