// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTWA2gSVGgsfcI25zW5Zhn5gZ6lNZGOh4',
    appId: '1:802051879682:android:7374e55819854547d9c81b',
    messagingSenderId: '802051879682',
    projectId: 'dw-job-timer-7',
    storageBucket: 'dw-job-timer-7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWZDK7qPdVxsxEz9zcjjt2IPSBlGRxMYY',
    appId: '1:802051879682:ios:2ceee57511a890dad9c81b',
    messagingSenderId: '802051879682',
    projectId: 'dw-job-timer-7',
    storageBucket: 'dw-job-timer-7.appspot.com',
    androidClientId: '802051879682-clq91efb8b7d657s5ug5at0ev1obb5fg.apps.googleusercontent.com',
    iosClientId: '802051879682-qnvkk9a4dr312k1fhce12f6jda9j888u.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobTimer',
  );
}
